server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /auth/ {
        proxy_pass http://search-api:8000;
    }

    location /admin/ {
        proxy_pass http://search-api:8000;
    }

    location /health {
        proxy_pass http://search-api:8000;
    }

    location /search/ {
        proxy_pass http://search-api:8000;
    }

    location /match/ {
        proxy_pass http://search-api:8000;
    }
}
